@createtables2;
SPOOL homework3.txt;
@Team_PKG;
@Team_PKG_Body;
@Player_PKG;
@Player_PKG_Body;
@Arena_PKG;
@Arena_PKG_Body;
Set serveroutput on;
SET LIN[ESIZE] 400;
select * from arena;
select * from team;
select * from player;
select * from team_player_arena;
@test;
@test2;
@test3;
select * from arena;
select * from team;
select * from player;
select * from team_player_arena;
SPOOL off;