-- Writen by Chet Michals
SET ECHO ON;
--
-- Problem 1
SELECT PLAYER_ID, PNAME FROM PLAYER WHERE POSITION = 'Point guard' and DRAFT_YEAR > 2002;
--
-- Problem 2
select ARENA.ANAME, ARENA.CITY from TEAM_PLAYER_ARENA 
INNER JOIN team on TEAM_PLAYER_ARENA.TEAM_ID = team.TEAM_ID
INNER JOIN arena on arena.ARENA_ID = TEAM_PLAYER_ARENA.ARENA_ID
 where team.city = 'LA';
--
-- Problem 3a 
select ARENA.Aname from TEAM_PLAYER_ARENA 
INNER JOIN team on TEAM_PLAYER_ARENA.TEAM_ID = team.TEAM_ID
INNER JOIN arena on arena.ARENA_ID = TEAM_PLAYER_ARENA.ARENA_ID
INNER JOIN PLAYER on PLAYER.PLAYER_ID = TEAM_PLAYER_ARENA.PLAYER_ID
where team.city = 'Charlotte'
and PLAYER.POSITION = 'Shooting guard';
--
-- Problem 3b
select ARENA.Aname from TEAM_PLAYER_ARENA 
INNER JOIN team on TEAM_PLAYER_ARENA.TEAM_ID = team.TEAM_ID
INNER JOIN arena on arena.ARENA_ID = TEAM_PLAYER_ARENA.ARENA_ID
INNER JOIN PLAYER on PLAYER.PLAYER_ID = TEAM_PLAYER_ARENA.PLAYER_ID
where team.city = 'Charlotte'
MINUS
select ARENA.Aname from TEAM_PLAYER_ARENA 
INNER JOIN team on TEAM_PLAYER_ARENA.TEAM_ID = team.TEAM_ID
INNER JOIN arena on arena.ARENA_ID = TEAM_PLAYER_ARENA.ARENA_ID
INNER JOIN PLAYER on PLAYER.PLAYER_ID = TEAM_PLAYER_ARENA.PLAYER_ID
where team.city = 'Charlotte'
and PLAYER.POSITION = 'Shooting guard';
--
-- Problem 4
(select ARENA.Aname, ARENA.CITY from TEAM_PLAYER_ARENA 
INNER JOIN team on TEAM_PLAYER_ARENA.TEAM_ID = team.TEAM_ID
INNER JOIN arena on arena.ARENA_ID = TEAM_PLAYER_ARENA.ARENA_ID
INNER JOIN PLAYER on PLAYER.PLAYER_ID = TEAM_PLAYER_ARENA.PLAYER_ID)
MINUS
(select ARENA.Aname, ARENA.CITY from TEAM_PLAYER_ARENA 
INNER JOIN team on TEAM_PLAYER_ARENA.TEAM_ID = team.TEAM_ID
INNER JOIN arena on arena.ARENA_ID = TEAM_PLAYER_ARENA.ARENA_ID
INNER JOIN PLAYER on PLAYER.PLAYER_ID = TEAM_PLAYER_ARENA.PLAYER_ID
where TEAM.TNAME = 'Bulls');